# Generated by Django 5.1 on 2024-09-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demand_prediction_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=50, unique=True)),
                ('seat_no', models.IntegerField()),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('travel_from', models.CharField(max_length=100)),
                ('travel_to', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=50)),
                ('max_capacity', models.IntegerField()),
                ('travel_from_to', models.CharField(max_length=200)),
            ],
        ),
    ]
