# Generated by Django 5.1.1 on 2024-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_bus_crewdetails_busshift_crewshiftpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=50)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('crew_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='crewshiftpreferences',
            name='crew',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='BusShift',
        ),
        migrations.DeleteModel(
            name='CrewDetails',
        ),
        migrations.DeleteModel(
            name='CrewShiftPreferences',
        ),
    ]
