# Generated by Django 5.1.1 on 2024-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_employee_remove_busshift_bus_remove_busshift_crew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_no', models.CharField(max_length=50)),
                ('bus_type', models.CharField(max_length=100)),
                ('ac_non_ac', models.CharField(max_length=10)),
                ('avg_mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_maintenance_date', models.DateField()),
                ('next_maintenance_date', models.DateField()),
                ('bus_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('join_date', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('assigned_bus_id', models.CharField(max_length=50)),
                ('assigned_route_id', models.CharField(max_length=50)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleManagement',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_no', models.CharField(max_length=50)),
                ('driver_id', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=255)),
                ('conductor_id', models.CharField(max_length=50)),
                ('conductor_name', models.CharField(max_length=255)),
                ('bus_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
