# Generated by Django 5.1.1 on 2024-10-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_userrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=255)),
                ('trip_id', models.CharField(max_length=255)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('return_start_time', models.TimeField(null=True)),
                ('return_end_time', models.TimeField(null=True)),
            ],
            options={
                'unique_together': {('route_id', 'trip_id')},
            },
        ),
    ]
