# Generated by Django 5.1.1 on 2024-10-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
